/*
 * Serves the FCM service worker at `/firebase-messaging-sw.js`.
 *
 * Generated by a route rather than dropped in public/ so it gets the real
 * NEXT_PUBLIC_FIREBASE_* values — a static file has no access to environment
 * variables, and the alternatives are hardcoding the project or adding a
 * build-time substitution step that fails silently when skipped.
 *
 * The path is fixed by convention: the Firebase SDK registers exactly
 * `/firebase-messaging-sw.js`, and a service worker only controls pages at or
 * below its own scope. Served from the root it covers the whole app.
 *
 * These are public client identifiers, already present in the JS bundle.
 */

export const dynamic = 'force-static'

const config = {
  apiKey: process.env.NEXT_PUBLIC_FIREBASE_API_KEY,
  authDomain: process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN,
  projectId: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID,
  storageBucket: process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET,
  messagingSenderId: process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID,
  appId: process.env.NEXT_PUBLIC_FIREBASE_APP_ID,
}

export function GET() {
  // `compat` builds: a classic service worker, which is what Firebase
  // registers, cannot use ES module imports.
  const body = `
importScripts("https://www.gstatic.com/firebasejs/10.12.2/firebase-app-compat.js");
importScripts("https://www.gstatic.com/firebasejs/10.12.2/firebase-messaging-compat.js");

firebase.initializeApp(${JSON.stringify(config)});

const messaging = firebase.messaging();

/**
 * The app's notification routes are Flutter paths; the web equivalents differ.
 * Kept in sync with webRoute() in lib/notifications.ts — an unmapped route
 * falls back to the notification list rather than a dead link.
 */
function webPath(route) {
  const map = {
    "/tenant/home": "/dashboard",
    "/tenant/inspections": "/dashboard/inspections",
    "/tenant/my-rentals": "/dashboard/rentals",
    "/tenant/issue-history": "/dashboard/issues",
    "/landlord/inspections": "/dashboard/requests",
  };
  return map[route] || "/dashboard/notifications";
}

messaging.onBackgroundMessage((payload) => {
  const data = payload.data || {};
  // Chat collapses per conversation so a burst from one thread replaces
  // rather than stacks — matching the app's Android tag / iOS thread-id.
  const tag =
    data.type === "chat_message" && data.conversationId
      ? "chat_" + data.conversationId
      : data.type || "clearrent";

  self.registration.showNotification(
    payload.notification?.title || "ClearRent",
    {
      body: payload.notification?.body || "",
      icon: "/logos/clearrent_mark_color.svg",
      badge: "/logos/clearrent_mark_color.svg",
      tag,
      renotify: true,
      data,
    }
  );
});

self.addEventListener("notificationclick", (event) => {
  event.notification.close();
  const url = webPath(event.notification.data?.route);
  // Focus an open tab rather than opening a second one.
  event.waitUntil(
    self.clients
      .matchAll({ type: "window", includeUncontrolled: true })
      .then((clients) => {
        for (const client of clients) {
          if ("focus" in client) {
            client.navigate(url);
            return client.focus();
          }
        }
        return self.clients.openWindow(url);
      })
  );
});
`.trim()

  return new Response(body, {
    headers: {
      'Content-Type': 'application/javascript; charset=utf-8',
      'Service-Worker-Allowed': '/',
      'Cache-Control': 'public, max-age=0, must-revalidate',
    },
  })
}
